#!/bin/bash

#============================================================================
# Detox Tool Feature Component Generator Script
# Category: welcome-features
# Description: Welcome page feature components (WelcomeHeader, WelcomeFeatureCard)
# Generated by: Task-Writer ScaffoldGenerator
#============================================================================

echo "🚀 Creating welcome feature components for detox-tool..."
echo "📁 Target: ./src/"

# Create target directory structure
mkdir -p src/components/features/welcome/

#!/bin/bash

# Scaffold script generated by Task Writer
# Generated on: 2025-07-01T01:16:17.420Z
# Source directory: /mnt/c/Projects/task-writer/frontend/app/src/components/features/welcome
# Target OS: cross-platform
# Directories: 0
# Files: 3
#
# This script will recreate the directory structure and files
# including the original file contents.

# Create files
# Create WelcomeFeatureCard.tsx
cat > "src/components/features/welcome/WelcomeFeatureCard.tsx" << 'EOF'
import React from 'react'
import { motion } from 'framer-motion'
import { ArrowRight } from 'lucide-react'
import type { WelcomeFeature } from '@/config/welcomeFeatures'

interface WelcomeFeatureCardProps {
  feature: WelcomeFeature
  index: number
  cardVariants: any
  prefersReducedMotion: boolean
  onFocus: (index: number) => void
  onBlur: () => void
  onAction: () => void
}

/**
 * Component for individual Welcome page feature cards
 * Follows architecture guide principles:
 * - Single responsibility: Feature card display and interaction
 * - Under 150 lines
 * - Clean props interface
 * - Accessibility focused
 */
const WelcomeFeatureCard: React.FC<WelcomeFeatureCardProps> = ({
  feature,
  index,
  cardVariants,
  prefersReducedMotion,
  onFocus,
  onBlur,
  onAction,
}) => {
  return (
    <motion.article
      variants={cardVariants}
      className={`bg-surface app-border overflow-hidden transition-all duration-300 group focus-within:ring-2 focus-within:ring-accent focus-within:ring-offset-2 focus-within:ring-offset-background ${
        prefersReducedMotion ? '' : 'motion-safe:hover:shadow-theme motion-safe:hover:scale-[1.02]'
      }`}
      aria-labelledby={`feature-${feature.id}-title`}
      role="region"
    >
      <div className="bg-gradient-to-r from-surface to-background px-6 py-4 app-border-b">
        <div className="flex items-center gap-3">
          <div 
            className={`page-icon transition-transform duration-300 ${prefersReducedMotion ? '' : 'motion-safe:group-hover:scale-110'}`} 
            role="img" 
            aria-hidden="true"
          >
            <feature.icon className="w-6 h-6 text-accent motion-safe:group-hover:text-accent-hover transition-colors" />
          </div>
          <h3 id={`feature-${feature.id}-title`} className="text-xl font-semibold text-text">
            {feature.title}
          </h3>
        </div>
      </div>
      
      <div className="p-6 space-y-6">
        {/* Description */}
        <p className="text-text-muted leading-relaxed">
          {feature.description}
        </p>

        {/* Action Button */}
        <button
          onClick={onAction}
          onFocus={() => onFocus(index)}
          onBlur={onBlur}
          className={`w-full flex items-center justify-center gap-2 px-4 py-3 text-base bg-accent hover:bg-accent-hover focus:bg-accent-hover app-border-accent rounded-md transition-all duration-300 text-text-background focus:outline-none focus:ring-2 focus:ring-accent focus:ring-offset-2 focus:ring-offset-background ${
            prefersReducedMotion ? '' : 'motion-safe:hover:shadow-theme motion-safe:hover:-translate-y-0.5 motion-safe:active:translate-y-0'
          }`}
          aria-label={feature.ariaLabel}
          type="button"
        >
          <ArrowRight 
            className={`w-4 h-4 transition-transform ${prefersReducedMotion ? '' : 'motion-safe:group-hover:translate-x-1'}`} 
            aria-hidden="true" 
          />
          <span>Get Started with {feature.title}</span>
        </button>
      </div>
    </motion.article>
  )
}

export default WelcomeFeatureCard
EOF

# Create WelcomeHeader.tsx
cat > "src/components/features/welcome/WelcomeHeader.tsx" << 'EOF'
import React from 'react'
import { motion } from 'framer-motion'
import { Sparkles } from 'lucide-react'

interface WelcomeHeaderProps {
  headerVariants: any
  prefersReducedMotion: boolean
}

/**
 * Component for Welcome page header
 * Follows architecture guide principles:
 * - Single responsibility: Header display and branding
 * - Under 100 lines
 * - Clean props interface
 * - Accessibility focused
 */
const WelcomeHeader: React.FC<WelcomeHeaderProps> = ({
  headerVariants,
  prefersReducedMotion,
}) => {
  return (
    <motion.header
      {...headerVariants}
      className="text-center"
    >
      <div className="bg-surface app-border overflow-hidden mb-6 motion-reduce:transform-none hover:shadow-theme transition-shadow duration-300">
        <div className="bg-gradient-to-r from-surface to-background px-6 py-8">
          <div className="flex items-center justify-center mb-4">
            <h1 className="text-3xl font-bold text-text flex items-center gap-3" id="welcome-title">
              Task Writer
              <div 
                className="page-icon flex items-center" 
                role="img" 
                aria-label="Task Writer application logo"
              >
                <Sparkles 
                  className={`text-accent w-8 h-8 ${prefersReducedMotion ? '' : 'motion-safe:animate-spin-slow motion-safe:hover:animate-pulse'}`}
                  aria-hidden="true"
                />
              </div>
            </h1>
          </div>
          <p className="text-base text-text-muted" id="welcome-subtitle">
            AI-Powered Development Assistant
          </p>
        </div>
      </div>
    </motion.header>
  )
}

export default WelcomeHeader
EOF

# Create index.ts
cat > "src/components/features/welcome/index.ts" << 'EOF'
// Welcome page feature components
export { default as WelcomeHeader } from './WelcomeHeader'
export { default as WelcomeFeatureCard } from './WelcomeFeatureCard'

// Re-export related hooks and config
export { useWelcomeAnimations } from '@/hooks/useWelcomeAnimations'
export { useWelcomeState } from '@/hooks/useWelcomeState'
export { getWelcomeFeatures, type WelcomeFeature } from '@/config/welcomeFeatures'
EOF


# Scaffold generation completed
echo "Scaffold generation completed successfully!"

echo "✅ welcome feature components created successfully!"
