#!/bin/bash

#============================================================================
# Detox Tool Component Generator Script
# Category: lib
# Description: Library utilities and helpers
# Generated by: Task-Writer ScaffoldGenerator
#============================================================================

echo "🚀 Creating lib for detox-tool..."
echo "📁 Target: ./src/"

# Create target directory structure
mkdir -p src/lib/
mkdir -p src/components/search
mkdir -p src/components/sidebar
mkdir -p src/components/menu
mkdir -p src/components/titlebar
mkdir -p src/pages/settings
mkdir -p src/contexts
mkdir -p src/utils
mkdir -p src/data
mkdir -p src/lib
mkdir -p src/types

#!/bin/bash

# Scaffold script generated by Task Writer
# Generated on: 2025-07-01T01:16:17.237Z
# Source directory: /mnt/c/Projects/task-writer/frontend/app/src/lib
# Target OS: cross-platform
# Directories: 0
# Files: 1
#
# This script will recreate the directory structure and files
# including the original file contents.

# Create files
# Create utils.ts
cat > "src/lib/utils.ts" << 'EOF'
import { type ClassValue, clsx } from 'clsx'
import { twMerge } from 'tailwind-merge'

// cn utility for merging Tailwind classes
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

// Other general utilities can be added here

EOF


# Scaffold generation completed
echo "Scaffold generation completed successfully!"

echo "✅ lib components created successfully!"
