#!/bin/bash

#============================================================================
# Detox Tool Component Generator Script
# Category: pages
# Description: Pages and route components
# Generated by: Task-Writer ScaffoldGenerator
#============================================================================

echo "🚀 Creating pages for detox-tool..."
echo "📁 Target: ./src/"

# Create target directory structure
mkdir -p src/pages/
mkdir -p src/components/search
mkdir -p src/components/sidebar
mkdir -p src/components/menu
mkdir -p src/components/titlebar
mkdir -p src/pages/settings
mkdir -p src/contexts
mkdir -p src/utils
mkdir -p src/data
mkdir -p src/lib
mkdir -p src/types

#!/bin/bash

# Scaffold script generated by Task Writer
# Generated on: 2025-07-01T01:16:17.121Z
# Source directory: /mnt/c/Projects/task-writer/frontend/app/src/pages
# Target OS: cross-platform
# Directories: 3
# Files: 1
#
# This script will recreate the directory structure and files
# including the original file contents.

# Create directories
mkdir -p "scaffold"
mkdir -p "settings"
mkdir -p "tasks"

# Create files
# Create WelcomePage.tsx
cat > "src/pages/WelcomePage.tsx" << 'EOF'
import { Home } from 'lucide-react'
import { motion } from 'framer-motion'
import { useWelcomeAnimations } from '@/hooks/useWelcomeAnimations'
import { useWelcomeState } from '@/hooks/useWelcomeState'
import { getWelcomeFeatures } from '@/config/welcomeFeatures'
import WelcomeHeader from '@/components/features/welcome/WelcomeHeader'
import WelcomeFeatureCard from '@/components/features/welcome/WelcomeFeatureCard'
import type { NavigationConfig } from '@/types/navigation'

/**
 * Refactored Welcome page component
 * Follows architecture guide principles:
 * - Single responsibility: Page orchestration and layout
 * - Under 150 lines (reduced from 247 lines)
 * - Clean separation of concerns via hooks and components
 * - Composition over complex logic
 */
const WelcomePage = () => {
  const {
    prefersReducedMotion,
    containerVariants,
    cardVariants,
    headerVariants,
  } = useWelcomeAnimations()

  const {
    announcement,
    handleOpenTab,
    handleKeyDown,
    handleFocus,
    handleBlur,
  } = useWelcomeState()

  const features = getWelcomeFeatures(handleOpenTab)

  return (
    <div 
      className="h-full overflow-y-auto flex items-center justify-center" 
      role="main" 
      aria-label="Welcome to Task Writer"
      onKeyDown={handleKeyDown}
      tabIndex={-1}
    >
      <div className="w-full max-w-6xl p-6">
        {/* Screen reader announcements */}
        <div 
          role="status" 
          aria-live="polite" 
          aria-atomic="true"
          className="sr-only"
        >
          {announcement}
        </div>

        <div className="space-y-6">
          {/* Header */}
          <WelcomeHeader 
            headerVariants={headerVariants}
            prefersReducedMotion={prefersReducedMotion}
          />

          {/* Features */}
          <motion.section
            variants={containerVariants}
            initial="hidden"
            animate="visible" 
            className="grid grid-cols-1 lg:grid-cols-2 gap-4"
            aria-labelledby="features-heading"
          >
            <h2 id="features-heading" className="sr-only">Main application features</h2>
            
            {features.map((feature, index) => (
              <WelcomeFeatureCard
                key={feature.id}
                feature={feature}
                index={index}
                cardVariants={cardVariants}
                prefersReducedMotion={prefersReducedMotion}
                onFocus={handleFocus}
                onBlur={handleBlur}
                onAction={() => feature.action(handleOpenTab)}
              />
            ))}
          </motion.section>
        </div>
      </div>
    </div>
  )
}

export default WelcomePage

// Export the navigation config for auto-discovery
export const navigationConfig: NavigationConfig = {
  id: 'welcome',
  label: 'Welcome',
  iconComponent: Home,
  showInSidebar: false,
  closable: true,
  order: 0,
}
EOF


# Scaffold generation completed
echo "Scaffold generation completed successfully!"

echo "✅ pages components created successfully!"
