#!/bin/bash

#============================================================================
# Detox Tool - Master Component Script Runner
# Runs all component generation scripts in the correct order
# Generated by: Task-Writer ScaffoldGenerator
#============================================================================

set -e  # Exit on any error

echo "🚀 Detox Tool - Master Component Generator"
echo "=========================================="
echo ""

# Check if we're in the right directory
if [ ! -f "package.json" ] || [ ! -d "frontend" ]; then
    echo "❌ Error: Please run this script from the detox-tool root directory"
    echo "   Expected structure: detox-tool/package.json and detox-tool/frontend/"
    exit 1
fi

# Change to frontend app directory
cd frontend/app

echo "📁 Working directory: $(pwd)"
echo ""

# Make all scripts executable
echo "🔧 Making scripts executable..."
chmod +x ../scripts/create-detox-*.sh
echo ""

# Run scripts in order based on implementation phases
scripts=(
    "create-detox-layout-components.sh"
    "create-detox-layout-hooks.sh"
    "create-detox-core-services.sh"
    "create-detox-navigation-config.sh"
    "create-detox-ui-components.sh"
    "create-detox-shared-components.sh"
    "create-detox-pages.sh"
    "create-detox-sidebar-components.sh"
    "create-detox-menu-components.sh"
    "create-detox-titlebar-components.sh"
    "create-detox-search-components.sh"
    "create-detox-contexts.sh"
    "create-detox-utils.sh"
    "create-detox-data.sh"
    "create-detox-lib.sh"
    "create-detox-electron-types.sh"
    "create-detox-spotlight-search-features.sh"
    "create-detox-tabbar-features.sh"
    "create-detox-welcome-features.sh"
    "create-detox-settings-features.sh"
    "create-detox-filetree-components.sh"
    "create-detox-shared-forms-complete.sh"
    "create-detox-settings-page-complete.sh"
)

total_scripts=${#scripts[@]}
current=0

for script in "${scripts[@]}"; do
    current=$((current + 1))
    echo "📦 [$current/$total_scripts] Running $script..."
    
    if [ -f "../scripts/$script" ]; then
        bash "../scripts/$script"
        echo "   ✅ $script completed"
    else
        echo "   ⚠️  Script not found: ../scripts/$script"
    fi
    echo ""
done

echo "🎉 All component scripts completed!"
echo ""
echo "📋 Next steps:"
echo "   1. Review generated components in ./src/"
echo "   2. Run: npm run lint -- --fix"
echo "   3. Run: npm run typecheck"
echo "   4. Test component imports and integration"
echo "   5. Continue with detox-tool specific customizations"
echo ""
echo "✨ Ready to build detox-tool with task-writer architecture!"
